version: '3.9'

services:
  backend_0:
    build: ./backend
    restart: always
    container_name: BACKEND_0
    volumes:
      - ./backend:/usr/backend
      - ./backend/node_modules:/usr/backend/node_modules
    environment:
      - CONTAINER_HOST=backend_0
    networks:
      - internal

    expose:
      - 3100

    depends_on:
      - mongo_db

  
  backend_1:
    build: ./backend
    restart: always
    container_name: BACKEND_1
    volumes:
      - ./backend:/usr/backend
      - ./backend/node_modules:/usr/backend/node_modules
    environment:
      - CONTAINER_HOST=backend_1
    networks:
      - internal
    expose:
      - 3100
    depends_on:
      - mongo_db


  mongo_db:
      image: mongo:latest
      container_name: mongo_db
      ports:
          - "27017:27017"
      networks: 
          - "internal"
      volumes: 
          - "mongo-data:/data/db"




  load_balancer:
    container_name: 'load_balancer'
    tty: true
    build: ./load_balancer
    ports:
    - "8082:80"
    networks:
    - internal
    depends_on:
    - backend_0
    - backend_1
    restart: always




networks: 
    internal:
        driver: bridge

volumes:
    mongo-data:
        driver: local